feat(dataStore_pref): show all the pref data and a sample
mocklets/pluto pull request #117
Opened 2022-03-27 10:28 UTC by rishabhsinghbisht

2022-03-27 10:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/plutolib/pluto?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/plutolib/pluto?pullRequest=117) before we can accept your contribution.<br/><hr/>**Rishabh singh bisht** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/plutolib/pluto?pullRequest=117) it.</sub>

2022-04-02 19:11 UTC, srtvprateek commented on datastore-pref-plugin-no-op/src/main/AndroidManifest.xml
> +    package="com.pluto.plugin.datastore.pref">
make it `com.pluto.plugins.datastore.pref`

2022-04-02 19:12 UTC, srtvprateek commented on datastore-pref-plugin-no-op/src/main/java/com/pluto/plugin/datastore/pref/DataStorePrefPlugin.kt
> +        version = "0.1-beta"
can take this from `BuildConfig`

2022-04-02 19:14 UTC, srtvprateek requested changes
.

2022-04-06 10:46 UTC, rishabhsinghbisht commented on datastore-pref-plugin-no-op/src/main/java/com/pluto/plugin/datastore/pref/DataStorePrefPlugin.kt
> +        version = "0.1-beta"
@srtvprateek is it build specific?

2022-04-06 19:32 UTC, srtvprateek approved these changes

2022-04-06 19:32 UTC, merged