fix: possible content convert exception
mocklets/pluto pull request #294
Opened 2023-11-25 22:06 UTC by epicadk

2023-11-26 08:42 UTC, srtvprateek requested changes

2023-11-26 08:42 UTC, srtvprateek commented on sample/src/main/java/com/sampleapp/functions/network/internal/ktor/KtorNetwork.kt
> +    install(PlutoKtorInterceptor)
@epicadk lets update the README.md also

2023-11-27 09:43 UTC, epicadk commented on sample/src/main/java/com/sampleapp/functions/network/internal/ktor/KtorNetwork.kt
> +    install(PlutoKtorInterceptor)
updated

2023-11-28 06:15 UTC, srtvprateek approved these changes

2023-11-28 06:15 UTC, merged